### PR TITLE
pull-stream is a dependency, not devDependency

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
This means that installing from npm currently doesn't work. Workaround is to do `npm i` in `./node_modules/pull-serializer`

At least it doesn't work for me. My npm version is:

```
$ npm -v
2.3.0
```

**Comment by pfraze** [comment]
good catch, thanks

**Comment by pfraze** [comment]
published `0.3.2`

**Comment by ralphtheninja** [comment]
Sawwweeeeet :+1:

**Pull request merged**
